# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StuToDo_Alpha' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StuToDo_Alpha
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseFirestoreSwift', '~> 8.0-beta'
  pod 'Loaf'
  pod 'FSCalendar'
  pod 'MBProgressHUD'
  pod 'SDWebImage'

end
